# service file is to establish connection between pods
apiVersion: v1
kind: Service
metadata:
  name: redis    # name is important with this IP will be created, so instead of connecting via IP we could use the name to connect
  labels:
    app: redis
spec:
  ports:
    - name: "redis-service"
      targetPort: 6379
      port: 6379
  selector:
    app: redis   #maps to pod with a label of "redis"