# service file is to establish connection between pods
apiVersion: v1
kind: Service
metadata:
  name: db    # name is important with this IP will be created, so instead of connecting via IP we could use the name to connect
  labels:
    app: db
spec:
  type: ClusterIP
  ports:
    - name: "db-service"
      targetPort: 5432
      port: 5432
  selector:
    app: db   #maps to pod with a label of "db"