# service file is to establish connection between pods
apiVersion: v1
kind: Service
metadata:
  name: vote    # name is important with this IP will be created, so instead of connecting via IP we could use the name to connect
  labels:
    app: vote
spec:
  type: NodePort
  ports:
    - name: "vote-service"
      targetPort: 80
      port: 8080
      nodePort: 31000
  selector:
    app: vote   #maps to pod with a label of "vote"